<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>Exe</OutputType>
	    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <None Update="MailMergeSimple.docx">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Office.Interop.Outlook" Version="15.0.4569.1507" />
	    <PackageReference Include="MicrosoftOfficeCore" Version="15.0.0" />
        <PackageReference Include="DevExpress.RichEdit.Core" Version="24.2.*" />
    </ItemGroup>
</Project>